services:
  << (service_name | default('homer', true)) >>:
    image: docker.io/b4bz/homer:v26.4.2
    restart: << restart_policy >>
    <%- if container_name %>
    container_name: << container_name >>
    <%- endif %>
    <%- if container_timezone %>
    environment:
      - TZ=<< container_timezone >>
    <%- endif %>
    <%- if traefik_enabled %>
    networks:
      << traefik_network >>:
    <%- endif %>
    <%- if not traefik_enabled %>
    ports:
      - "<< ports_http >>:8080"
    <%- endif %>
    volumes:
      - ./assets:/www/assets
    <%- if traefik_enabled %>
    labels:
      - traefik.enable=true
      - traefik.docker.network=<< traefik_network >>
      - traefik.http.services.<< (service_name | default('homer', true)) >>-web.loadBalancer.server.port=8080
      - traefik.http.routers.<< (service_name | default('homer', true)) >>-http.service=<< (service_name | default('homer', true)) >>-web
      - traefik.http.routers.<< (service_name | default('homer', true)) >>-http.rule=Host(`<< traefik_host >>.<< traefik_domain >>`)
      - traefik.http.routers.<< (service_name | default('homer', true)) >>-http.entrypoints=<< traefik_entrypoint >>
      <%- if traefik_tls_enabled %>
      - traefik.http.routers.<< (service_name | default('homer', true)) >>-https.service=<< (service_name | default('homer', true)) >>-web
      - traefik.http.routers.<< (service_name | default('homer', true)) >>-https.rule=Host(`<< traefik_host >>.<< traefik_domain >>`)
      - traefik.http.routers.<< (service_name | default('homer', true)) >>-https.entrypoints=<< traefik_tls_entrypoint >>
      - traefik.http.routers.<< (service_name | default('homer', true)) >>-https.tls=true
      - traefik.http.routers.<< (service_name | default('homer', true)) >>-https.tls.certresolver=<< traefik_tls_certresolver >>
      <%- endif %>
    <%- endif %>

<%- if traefik_enabled %>
networks:
  << traefik_network >>:
    external: true
<%- endif %>
