
---
services:
  << (service_name | default('mariadb', true)) >>:
    image: docker.io/library/mariadb:12.2.2
    restart: << restart_policy >>
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=<< database_name >>
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    ports:
      - "<< ports_mariadb >>:3306"
    volumes:
      - << ((volume_data_name | default('', true) | string | trim) if ((volume_data_name | default('', true) | string | trim) and ((volume_data_name | default('', true) | string | trim) | lower) not in ['true', 'false', 'none', 'null']) else ((service_name | default('mariadb', true)) ~ "_data")) >>:/var/lib/mysql

volumes:
  << ((volume_data_name | default('', true) | string | trim) if ((volume_data_name | default('', true) | string | trim) and ((volume_data_name | default('', true) | string | trim) | lower) not in ['true', 'false', 'none', 'null']) else ((service_name | default('mariadb', true)) ~ "_data")) >>:
    driver: local
