---
apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: << resource_name >>
spec:
  image:
    repository: twingate/connector
    tag: 1.88.0
  name: << connector_name >>
  hasStatusNotificationsEnabled: << status_notifications | lower >>
