---
apiVersion: v1
kind: Secret
metadata:
  name: << resource_name >>
  namespace: << namespace >>
type: Opaque
stringData:
  customer-number: << customer_number >>
  api-key: << api_key >>
  api-password: << api_password >>
