---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: << resource_name >>
spec:
  secretName: << secret_name >>
  duration: << duration >>
  renewBefore: << renew_before >>
  issuerRef:
    name: << issuer_name >>
    kind: << issuer_kind >>
    group: << issuer_group >>
  <%- if common_name %>
  commonName: << common_name >>
  <%- endif %>
  dnsNames:
    <%- for name in dns_names.split(',') %>
    - << name.strip() >>
    <%- endfor %>
  privateKey:
    algorithm: << private_key_algorithm >>
    size: << private_key_size >>
    rotationPolicy: << private_key_rotation_policy >>
  usages:
    - digital signature
    - key encipherment
    - server auth
