#!/usr/bin/env python3
"""Regression: library inputs/files must never carry credential material."""
import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
removed = json.loads((root / 'scripts/removed-credential-inputs.json').read_text())
errors = []
for manifest in sorted(root.glob('*/*/template.json')):
    data = json.loads(manifest.read_text())
    slug = manifest.parent.relative_to(root).as_posix()
    names = {v['name'] for s in data['variables'] for v in s['items']}
    for section in data['variables']:
        if section.get('toggle') and section['toggle'] not in names:
            errors.append(f'{slug}: dangling section toggle {section["toggle"]}')
        for item in section['items']:
            if item['type'] == 'secret' or item['name'] in removed.get(slug, []):
                errors.append(f'{slug}: credential input {item["name"]}')
        for entry in [section, *section['items']]:
            for need in entry.get('needs', []):
                name = re.split(r'[=!<>]', need)[0].strip()
                if name not in names:
                    errors.append(f'{slug}: dangling condition {need}')
    if re.search(r'"(?:generator|autogenerated)"\s*:', manifest.read_text()):
        errors.append(f'{slug}: credential generator')
    for path in (manifest.parent / 'files').rglob('*'):
        if not path.is_file():
            continue
        text = path.read_text()
        if path.name.startswith('.env'):
            errors.append(f'{path}: generated environment file')
        if re.search(r'^\s*kind:\s*Secret\s*$', text, re.M):
            errors.append(f'{path}: generated Secret content')
        for tag in re.findall(r'<[<%].*?(?:>>|%>)', text, re.S):
            for name in removed.get(slug, []):
                if re.search(r'\b' + name + r'\b', tag):
                    errors.append(f'{path}: credential render reference {name}')
        if data['kind'] in {'compose', 'swarm'}:
            for name, operator in re.findall(r'(?<!\$)\$\{(\w+)(:?[-?]?)', text):
                if re.search(r'PASSWORD|SECRET|TOKEN|ENCRYPTION_KEY|API_KEY|ACCESS_KEY|WEBPASSWORD', name) and not name.endswith(('_FILE', '_NAME')) and operator != ':?':
                    errors.append(f'{path}: credential {name} needs a required reference without a default')
assert not errors, '\n'.join(errors)
print('Credential boundary passed for all library templates.')
