---
- name: Manage Checkmk host
  hosts: all
  gather_facts: false
  tasks:
    - name: "Create or update host in Checkmk"
      checkmk.general.host:
        server_url: "<< checkmk_protocol >>://<< checkmk_server >>"
        site: << checkmk_site >>
        automation_user: << checkmk_user >>
        automation_secret: "{{ lookup('ansible.builtin.env', 'CHECKMK_PASSWORD', default=undef()) }}"
        name: << host_name >>
        attributes:
          ipaddress: << host_ip >>
        folder: << host_folder >>
        state: "present"
      no_log: true
      delegate_to: localhost
      run_once: true
