---
services:
  << service_name >>:
    image: docker.io/louislam/uptime-kuma:2.3.2
    container_name: << container_name >>
    restart: << restart_policy >>
    ports:
      - "<< ports_http >>:3001"
    volumes:
      - << volume_data_name if volume_data_name else 'uptimekuma-data' >>:/app/data

volumes:
  << volume_data_name if volume_data_name else 'uptimekuma-data' >>:
    driver: local
